version: "3"
services:
  database_store:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 33066:3306
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - spark-network
      - store-network
  adminer:
    image: adminer
    ports:
      - 8002:8080
    networks:
      - store-network


  #Spark
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    networks:
      - spark-network
  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
      - SPARK_DRIVER_MEMORY=2G
      - SPARK_EXECUTOR_MEMORY=2G
      - SPARK_WORKLOAD=worker
    networks:
      - spark-network
  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
      - SPARK_DRIVER_MEMORY=2G
      - SPARK_EXECUTOR_MEMORY=2G
      - SPARK_WORKLOAD=worker
    networks:
      - spark-network


  spark-app:
    image: spark-app:v1
    build:
      context: ./spark-example
      dockerfile: spark.dockerfile
    environment:
      DOCKER_INSTANCE: 1
    ports:
      - 5004:5004
    networks:
      - spark-network
    depends_on:
      - spark-master
      - database_store
  
  #Blockchain
  ganache-cli:
    image: trufflesuite/ganache-cli
    ports:
      - 8545:8545
    networks:
      - store-network
    command: 
      - "--account=0xb64be88dd6b89facf295f4fd0dda082efcbe95a2bb4478f5ee582b7efe88cf60, 100000000000000000000"
  
  #Web services
  owner:
    image: owner:v1
    build:
      context: .
      dockerfile: owner.dockerfile
    environment:
      DOCKER_INSTANCE: 1
    ports:
      - 5001:5001
    depends_on:
      - spark-app
      - database_store
      - ganache-cli
    networks:
      - store-network
      - spark-network
  customer:
    image: customer:v1
    build:
      context: .
      dockerfile: customer.dockerfile
    environment:
      DOCKER_INSTANCE: 1
    ports:
      - 5002:5002
    depends_on:
      - database_store
      - ganache-cli
    networks:
      - store-network
  courier:
    image: courier:v1
    build:
      context: .
      dockerfile: courier.dockerfile
    environment:
      DOCKER_INSTANCE: 1
    ports:
      - 5003:5003
    depends_on:
      - database_store
      - ganache-cli
    networks:
      - store-network
networks:
  spark-network:
  store-network: