version: "3"
services:
  database:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 33066:3306
    volumes:
      - ./init:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    ports:
      - 8081:8080