version: "3"
services:
  database_auth:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./init:/docker-entrypoint-initdb.d
  adminer:
    image: adminer
    ports:
      - 8001:8080
  auth:
    image: auth:v1
    build:
      context: .
      dockerfile: auth.dockerfile
    environment:
      DOCKER_INSTANCE: 1
    ports:
      - 5000:5000